### PR TITLE
Make message editing use actual regexes

### LINKED ISSUE #197: Feature request: edit syntax should actually be regex
right now s/blah/new/ is just a string replace and is /g - it should be real regex.

### PR DESCRIPTION
**Pull request by terminalmage**
Resolves #197

### CODE REVIEW

**Comment by terminalmage** [comment]
@rawdigits Do you think it might be better to hide this behind a weechat option (e.g. ``/set python.slack_extension.edit_with_regex 1``)? If so, what should be the default behavior, ``str.replace()`` or ``re.sub()``?

This needs documentation in **README.md** regardless, so whatever the decision I'll need to push an additional commit before this would be merged.

**Comment by rawdigits** [comment]
thanks! we are discussing this and whether it needs to be behind an option. perhaps it is fine to make it the new default. we'll test and merge it soon.

**Comment by terminalmage** [comment]
Great! We should also document that the updated functionality allows for a ``#`` to be used as the regex delimiter.

**Comment by trygveaa** [comment]
Any progress on this? Would be nice to have the functionality.

To voice my opinion on the question above, if you want to allow replacement without regex I think it should rather be as another syntax, instead of adding an option for it.

**Pull request closed without merging**
