### PR TITLE
switch to buffer on query

### PR DESCRIPTION
**Pull request by scharfie**
With this PR, `/query USERNAME` will automatically switch to the newly created buffer.

### CODE REVIEW

**Comment by pbrisbin** [comment]
FWIW, this is working well for me.

**Comment by rawdigits** [comment]
This seems like a reasonable thing to do, but I'd prefer for there to be a configurable option for the old behavior. I've become used to opening buffers as a reminder to talk to someone, and often don't want to jump into a buffer and back out because it will move the read marker.

**Comment by pbrisbin** [comment]
That's a fair point. I turned this on mostly b/c the newly opened query buffer gets stuck in "loading..." until I go to it. Maybe that's a separate bug worth reporting?

**Comment by rawdigits** [comment]
The "loading..." thing is related to keeping redraws of the buffer list to a minimum. I've just fixed that one here (I think?): https://github.com/rawdigits/wee-slack/commit/5f5885185b10da6ea1ff4c791e17803a2e0ff22c

**Comment by pbrisbin** [comment]
Oh nice. Maybe that'll also fix a "stuck" typing indicator. I'll test tomorrow.

**Comment by JohnMaguire** [comment]
Given that default behavior in IRC seems to be switching to the window on `/query`, perhaps that should be the default w/ a boolean to switch to old behavior?

If that sounds reasonable, I can try to add the config option at some point this week to finish out this PR. (Thanks @rawdigits for wee-slack, and @scharfie  for the PR!)

**Comment by rawdigits** [comment]
@JohnMaguire having the option seems reasonable to me, if you make a PR I'll make sure it gets in.

**Comment by rawdigits** [comment]
Thanks! Did this, and made it optional. (defaults to on) - going to close this, as was quicker to just type the cpl of lines as opposed to merge dance.

**Comment by rawdigits** [comment]
https://github.com/rawdigits/wee-slack/commit/027a2218948558825e67c7efe50b1226107aafa8

**Pull request closed without merging**
