### PR TITLE
Rewrite ``unfurl_refs``

### PR DESCRIPTION
**Pull request by calve**
Digging into weird ``UnicodeDecodeException`` bugs I experienced, I ended up rewritting the ``unfurl_refs()`` function. 

Well, now itworks®

### CODE REVIEW

**Comment by tfheen** [comment]
I don't think this will work, unfurl_refs also handles other cases.  See https://github.com/rawdigits/wee-slack/blob/master/_pytest/test_unfurl.py for some inputs and outputs.

**Comment by calve** [comment]
I wasn't aware of this test. Could you document how am I supposed to run it ?

**Comment by tfheen** [comment]
]] calve 

> I wasn't aware of this test. Could you document how am I supposed to run it ?

On my system (with python-pytest installed), just run `py.test` in the
root of the checkout.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by calve** [comment]
Indeed.

I updated the code to handle all tested patterns.

**Comment by calve** [comment]
Any update on it ?

**Comment by rawdigits** [comment]
I'll check it out.

**Comment by rawdigits** [comment]
Hi calve - I tested this out with the profiler and it is sometimes the case, the regex version is actually slightly slower than the ugly brute force method currently used. I agree the code is MUCH better to look at, and am thinking of ways we can use your code without any slowdown.

The slowdown is mostly related to reading the cache re-parsing every message on startup. Forthcoming changes where we save a copy of the 'rendered' message for future use may mean we can use this code without any measurable impact to performance.

**Comment by calve** [comment]
Rebased. Could you share me your performance test script ?

Also looks like the test suite is broken. Last commit which successfully build appears to be d6652ae

**Comment by rawdigits** [comment]
Ya, need to fix testing!

I'll just leave the performance stuff here @calve :

```
import cProfile

p = cProfile.Profile()
p.enable()
counter = 1

#needed because otherwise no new data comes in
def profiler_write_cb(data, remaining):
    global counter, p
    p.dump_stats('/tmp/stats/asdf_{}'.format(counter))
    p.enable()
    counter += 1
    return w.WEECHAT_RC_OK


w.hook_timer(1000 * 5, 0, 0, "profiler_write_cb", “")
```

the above will write a file in `/tmp/stats/` every 5 seconds. it can be parsed with:

```
import pstats
p = pstats.Stats('asdf_1')
p.sort_stats('tottime').print_stats(20)
p.sort_stats('cumulative').print_stats(20)
```

**Comment by calve** [comment]
I just pushed a rebased patch against the current master.

**Comment by rawdigits** [comment]
Thanks for this @calve - makes the code much more readable. :smile:

**Pull request merged**
