### PR TITLE
Ignore command not executed in a slack buffer

### LINKED ISSUE #191: Error with msg hook, when using /say or /msg *
I have some aliases and scripts that use the /say command, that use /msg *.
From /help msg:

`target: nick or channel (may be mask, '*' = current channel)`
My theory is that slack hooks /msg and parses it wrongly.

Error looks like this:

```

1242             weechat              │ This command must be used in a slack buffer
1242             weechat          =!= │ python: function "msg_command_cb" must return a
                                      │ valid value                                      
1242             weechat          =!= │ python: error in function "msg_command_cb"
```

### PR DESCRIPTION
**Pull request by bendem**
Commands query, join, part, leave, topic are not specific to slack.
Using them in an irc context is valid and should not trigger errors
or messages.

Fixes #191 and #137

### CODE REVIEW

**Comment by tfheen** [comment]
Thanks for the PR!

This change means that we lose the error message for the commands which are specific to slack, though.  Can you split the functionality so that we keep that for those which are specific to slack, but adds your functionality to query, join, part, etc?

**Comment by bendem** [comment]
I'm not sure I understand, I only added `@slack_buffer_required` to the handlers of the commands that are **not** specific to slack.

**Comment by tfheen** [comment]
No, you also changed the implementation of `@slack_buffer_required` so that it no longer gives an error message.

This means that if you do `/slack upload` in a non-slack buffer today, you'd get an error. With your patch, it silently fails.

**Comment by tfheen** [comment]
I ended up redoing this, so closing this PR. Thanks for the inspiration, though. :-)

**Pull request closed without merging**
