### PR TITLE
Fixed slack talk, remove one extra "not"

### PR DESCRIPTION
**Pull request by marczis**
The fix for my bug report. Looks like you forget a "not" in that line.
Tested and seems to fix the issue.
Thanks !

### CODE REVIEW

**Comment by trygveaa** [comment]
I agree that there's an issue here, but I'm not sure if this is the correct fix. The code was like this before, and this commit changed it: https://github.com/rawdigits/wee-slack/pull/172/commits/6b53c203c50d44add1e33facb4159a4e6d573b2e

**Comment by trygveaa** [comment]
Also, see #234 which changes the same code in a different way.

**Comment by marczis** [comment]
Ahw, sorry I'm pressing wrong buttons. Wondering if now, my second commit is added to this pull request.. I added an extra error checking.

**Comment by rawdigits** [comment]
hi @marczis - merging #234 means this wont' merge cleanly. want to resubmit with just the valueerror fix? (just wanted you to get credit for it vs me just adding it in)

**Comment by marczis** [comment]
no worries about my credit :) I really did nothing extra with this, just
merge in the simplest way for you! Thanks!

**Pull request closed without merging**
