### PR TITLE
Fix up formatting of join/part/topic messages

### PR DESCRIPTION
**Pull request by tfheen**
Somewhat fixes https://github.com/rawdigits/wee-slack/issues/54, at least they're now shown as the right type of activity.

### CODE REVIEW

**Comment by rawdigits** [comment]
I wonder if it might be useful to allow buffer_prnt to accept a set of weechat tags as a list arg?

**Comment by tfheen** [comment]
Sure, I can implement that if you'd prefer that approach instead.

**Comment by rawdigits** [comment]
thanks! i'm gonna test this out and merge if all is well.

**Comment by rawdigits** [comment]
This is working well for me. thank you for the fixes!

**Pull request merged**
